name: Daily Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scraper.py

      - name: Commit updated DB
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
          echo "Checking for DB..."
          ls -l scripts/compromised_domains.db || echo "DB not found"
      
          echo "Staging DB file..."
          git add -f scripts/compromised_domains.db || echo "No file to add"
      
          echo "Trying to commit..."
          git commit -m "Auto-update DB from scraper" || echo "Nothing to commit"
      
          echo "Pushing..."
          git push || echo "Nothing to push"

      - name: Notify on failure
        if: failure()
        run: echo "Scraper failed! Check logs."
